---
- hosts: all
  become: yes
  tasks:
    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/1.24.1/docker-compose-{{ ansible_facts['system'] }}-{{ ansible_facts['architecture'] }}"
        dest: /usr/local/bin/docker-compose
        mode: '0755'
